logger:
  endpoints:
    - endpoint:
        type: "logging"
        name: "RemoteLog"
        class: "LogMessage"
        topic: "/RemoteLog"
        QoS: 10

knowledgeIn:
  properties:

knowledgeOut:
  properties:

eventIn:
  properties:

eventOut:
  properties:


mqtt_broker: "192.168.56.1"
mqtt_port: 1883

mqtt_subscribe_topics:
  - "/Scan"

mqtt_publish_topics:
  - "monitor/event"

redis_host: "192.168.56.1"
redis_port: 6379

logging:
  level: "DEBUG"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "MAPE_test.log"

knowledge_config:
  storage_type: "global"
  redis_host: "192.168.56.1"
  redis_port: 6379
  redis_db: 0